# Generated by Django 5.2 on 2026-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type_name', models.CharField(max_length=100, verbose_name='Тип материала')),
                ('deficiency_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент брака материала ')),
            ],
        ),
    ]
