# Generated by Django 5.2 on 2026-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ЗАО', 'ЗАО'), ('ОАО', 'ОАО'), ('ООО', 'ООО'), ('ПАО', 'ПАО')], max_length=50, verbose_name='Тип партнера')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование партнера')),
                ('ceo', models.CharField(max_length=100, verbose_name='Директор')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('phone_number', models.PositiveBigIntegerField(verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('taxpayer_number', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('rating', models.PositiveIntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
