# Generated by Django 5.2 on 2026-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=100, verbose_name='Тип проудкции')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент типа продукции')),
            ],
        ),
    ]
