# Generated by Django 5.2 on 2026-05-10 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование продукции')),
                ('sku', models.PositiveIntegerField(verbose_name='Артикул')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная стоимость для партнера')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_types.producttype', verbose_name='Тип продукции')),
            ],
        ),
    ]
